services:
  mongo:
    image: mongo:7
    container_name: fibrito-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: fibrito-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:adminpass@mongo:27017
      MONGO_DB: fibrito
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  mongo_data:
